version: '3.7'

services:
  db:
    platform: linux/x86_64
    build:
      context: ./mysql
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 1s
      timeout: 10s
      retries: 10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypass"
    volumes:
      - mysql_orders_database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    environment:
      - DBCONN=myuser:mypass@tcp(db:3306)/database
      - ENV=production
    depends_on:
      db: 
        condition: service_healthy

networks:
  default:
volumes:
  mysql_orders_database: